saleor/app-sdk

README.md
package.json
pnpm-lock.yaml

- bumped the tsup during investigation of the watch mode issues
- fix the watch mode. Now files will properly appear in the dist folder
- updated with instructions how to develop SDK locally

Local development 

---

src/middleware.ts

Handle missing webhook signature header

---

.eslintrc
docs/apl.md
package.json
src/APL/apl.ts
src/APL/index.ts
src/middleware.test.ts
src/middleware.ts

Introduce a common interface for auth data.

Introduce APL interface

---

package.json
src/middleware/index.ts

- fix missing JWT middleware export
- fix build modules config

Fix export from new modules

---

CODEOWNERS
README.md
docs/CODEOWNERS
docs/debugging.md

app-sdk introduced DEBUG integration, this PR adds docs for that

Add docs about debugging

---

.release-it.json
package.json
pnpm-lock.yaml

Using setup from saleor dashboard.

Install and configure release-it

---

package.json
pnpm-lock.yaml

Since `pnpm` is used for publishing, I removed `np` so it doesn't confuse us
Let's introduce `release-it` soon

Remove `np` packge

---

package.json
pnpm-lock.yaml
src/APL/vercel-apl.test.ts
src/APL/vercel-apl.ts

- add missing tests for set method
- fix setting up variables

Fix Vercel APL set method + add tests for it

---

src/app-bridge/app-bridge-state.test.ts
src/app-bridge/app-bridge-state.ts
src/app-bridge/app-bridge.ts
src/app-bridge/events.ts

Dashboard will be able to inform app about changed locale

Add support for locale change

---

docs/api-handlers.md
package.json
pnpm-lock.yaml
src/handlers/next/create-app-register-handler.test.ts
src/handlers/next/create-app-register-handler.ts
src/handlers/next/create-manifest-handler.test.ts
src/handlers/next/create-manifest-handler.ts
src/handlers/next/index.ts
src/handlers/next/readme.md
src/handlers/readme.md
src/index.ts
src/infer-webhooks.ts
src/middleware/with-base-url.ts
tsup.config.ts

This PR contributes to lean app templates, allowing sleek and minimal creation of handlers in Next
In the future, we will transform SDK to monorepo with SDK core + separate React, Next, Remix etc

Add Handler factories

---

package.json
pnpm-lock.yaml
src/app-bridge/index.ts
src/app-bridge/use-dashboard-token.ts
src/app-bridge/with-authorization.tsx
src/util/index.ts
src/util/is-in-iframe.ts
src/util/use-is-mounted.ts

Auth features

---

.husky/pre-push
src/APL/apl.ts
src/APL/file-apl.ts
src/APL/vercel-apl.test.ts
src/APL/vercel-apl.ts
src/handlers/next/create-app-register-handler.test.ts
src/handlers/next/create-app-register-handler.ts
src/index.ts
src/middleware/index.ts
src/middleware/with-registered-saleor-domain-header.test.ts
src/middleware/with-registered-saleor-domain-header.ts
src/middleware/with-saleor-app.test.ts
src/middleware/with-saleor-app.ts
src/saleor-app.test.ts
src/saleor-app.ts

This introduces early SaleorApp class that should be an entry point for app setup and config

Add central SaleorApp instance

---

src/APL/vercel-apl.test.ts
src/APL/vercel-apl.ts
src/app-bridge/use-dashboard-token.ts
src/middleware/with-jwt-verified.ts

Waiting for https://github.com/saleor/saleor/pull/10852 to complete. For now, iss check must be disabled, or apps are not working

Disable token iss validation

---

src/APL/apl.ts
src/APL/file-apl.ts
src/APL/vercel-apl.ts
src/handlers/next/create-app-register-handler.test.ts
src/handlers/next/create-app-register-handler.ts

This fixes too eager APL check, causing it failing on envs before they could have been set

Fix checking APL configuration state

---

docs/settings-manager.md
package.json
src/settings-manager/index.ts
src/settings-manager/metadata-manager.test.ts
src/settings-manager/metadata-manager.ts
src/settings-manager/settings-manager.ts
tsup.config.ts

Closes #60 
PR introduces a metadata manager with support for different domains.

Add metadata manager

---

.eslintrc
.prettierignore
docs/apl.md
src/APL/index.ts
src/APL/upstash-apl.test.ts
src/APL/upstash-apl.ts

Add Upstash APL

---

src/settings-manager/encrypted-metadata-manager.test.ts
src/settings-manager/encrypted-metadata-manager.ts
src/settings-manager/index.ts
src/settings-manager/metadata-manager.ts

Closes #83
Extend settings manager with encryption methods.

Encrypted metadata

---

src/APL/file-apl.test.ts
src/APL/file-apl.ts

Change behavior when FileAPL reads file that doesnt exist to fallback

---

package.json
src/app-bridge/actions.ts
src/app-bridge/next/index.ts
src/app-bridge/next/route-propagator.tsx
tsup.config.ts

- New action - UpdateRoute
- hook and component that automatically syncs next router with dashboard

Add routing changing actions and RoutePropagator

---

docs/apl.md
src/APL/index.ts
src/APL/rest-apl.ts
src/has-prop.ts

Add RestAPL originally created by @krzysztofwolski here https://github.com/saleor/saleor-app-template/blob/draft-rest-apl/lib/RestAPL.ts

Add REST APL

---

package.json

This copies readme file to /dist, so its published to npm

Copy readme on build

---

src/get-app-id.ts
src/handlers/next/create-protected-handler.ts
src/handlers/next/index.ts
src/handlers/next/process-async-saleor-webhook.ts
src/handlers/next/process-protected-handler.test.ts
src/handlers/next/process-protected-handler.ts
src/handlers/next/saleor-async-webhook.ts
src/infer-webhooks.ts
src/verify-jwt.test.ts
src/verify-jwt.ts

Close #104 
Usage example can be found here: https://github.com/saleor/saleor-app-template/pull/119

Add protected handlers for next

---

docs/protected-handlers.md

Add protected handler docs

---

src/handlers/next/create-app-register-handler.test.ts
src/handlers/next/create-app-register-handler.ts

Check app id during the registration

---

package.json
pnpm-lock.yaml
src/app-bridge/fetch.test.ts
src/app-bridge/fetch.ts
src/app-bridge/index.ts
src/setup-tests.ts

Will add docs when this is released (eg in RC), tested/added to template

Add authenticated fetch

---

src/APL/has-auth-data.ts
src/APL/saleor-cloud-apl.test.ts
src/APL/saleor-cloud-apl.ts

Use b64url and fix incoming data validation

---

src/handlers/next/create-protected-handler.ts
src/handlers/next/process-protected-handler.ts
src/has-permissions-in-jwt-token.ts
src/has-permissions.in-jwt-token.test.ts
src/verify-jwt.test.ts
src/verify-jwt.ts

Add an optional array of the required permissions to be check in protected handlers

Permission check for the protected handler

---

src/APL/saleor-cloud-apl.ts

Add more debug messages to SaleorCloudAPL

---

docs/protected-handlers.md

Add documentation part after @orzechdev feedback on this

Add note about protected handler

---

.changeset/slow-squids-hope.md
docs/api-handlers.md
src/handlers/next/create-app-register-handler.test.ts
src/handlers/next/create-app-register-handler.ts

Add hooks to createAppRegsiterHandler

---

.changeset/big-beans-grab.md
src/APL/upstash-apl.test.ts
src/APL/upstash-apl.ts

Improve error messages in UpstashAPL

---

.changeset/rotten-clocks-sell.md
package.json
pnpm-lock.yaml

Remove @types/node-fetch dep

---

.changeset/friendly-melons-approve.md
.changeset/long-hornets-yawn.md
.changeset/strong-rings-help.md
docs/apl.md
package.json
src/APL/apl.ts
src/APL/env-apl.test.ts
src/APL/env-apl.ts
src/APL/index.ts
src/handlers/next/saleor-webhooks/process-saleor-webhook.ts

```[tasklist]
```
Proof of concept:
https://github.com/lkostrowski/test-env-apl
https://github.com/lkostrowski/test-env-apl/blob/main/src/saleor-app.ts
First installation under the flag prints secrets
Envs set in vercel:
POC fetches APL from cloud function and prints it on frontend

Add EnvAPL

---

.changeset/great-dogs-cheer.md
src/types.ts

rel
https://github.com/saleor/apps/issues/156

Add requiredSaleorVersion field to AppManifest

---

.changeset/eight-wombats-drop.md
src/APL/upstash-apl.test.ts
src/APL/upstash-apl.ts

Fix missing serialization of the whole request send to the Upstash

Fix UpstashAPL serialization of the AuthData

---

src/settings-manager/settings-manager.ts

No changeset, because its not yet released

Change signature of SettingsManager interface, because it was incorrect in dts

---

.changeset/gorgeous-coats-rule.md
src/types.ts

Added definitions for new async events:
- `CHECKOUT_FULLY_PAID`
- `GIFT_CARD_SENT`

Update async webhook enum

---

.changeset/wicked-jobs-exist.md
docs/protected-handlers.md
src/handlers/next/process-protected-handler.test.ts
src/handlers/next/process-protected-handler.ts
src/util/extract-user-from-jwt.ts

Now app can easily save what user performed operations. For example when config is saved, app can write "last time updated {date} by {user.email}"

Extend protectedHandler to contain user object with email and permissions

---

docs/apl.md

Remove retes from code examples

Update APL docs

---

.changeset/lazy-ducks-add.md
docs/api-handlers.md
src/handlers/next/create-manifest-handler.test.ts
src/handlers/next/create-manifest-handler.ts

1. Removes retes  from this handler
2. Add context.request
3. adds docs

add request to createManifestHandler context

---

.changeset/purple-yaks-flash.md
docs/app-bridge.md
src/app-bridge/app-bridge-state.ts
src/app-bridge/app-bridge.test.ts
src/app-bridge/app-bridge.ts
src/app-bridge/events.test.ts
src/app-bridge/events.ts

Tested with Dashboard here:
https://github.com/saleor/saleor-dashboard/pull/3789

Add saleor versions to app bridge

---

.changeset/nine-hotels-rule.md
.husky/pre-commit
package.json
pnpm-lock.yaml
src/APL/index.ts
src/APL/vercel-kv/index.ts
src/APL/vercel-kv/vercel-kv-apl.test.ts
src/APL/vercel-kv/vercel-kv-apl.ts

Docs will follow when tested and moved out of experimental

Initial implementation of VercelKV apl

---

.changeset/fuzzy-pans-develop.md
src/APL/vercel-kv/index.ts
src/APL/vercel-kv/vercel-kv-apl.test.ts
src/APL/vercel-kv/vercel-kv-apl.ts

vercel kv exported as non-experimental

---

codecov.yml

Set CodeCov to be in informational mode: [docs.codecov.com/docs/commit-status#informational](https://docs.codecov.com/docs/commit-status#informational)

Update CodeCov to be informational

---

codecov.yml

The same as in https://github.com/saleor/app-sdk/pull/392

Update CodeCov to be informational for v0.x branch
