src/middleware.ts

I want to merge this because it fixes an 500 Internal Server Error when JWS from request is malformed.
We can simply pass JWKS object into jose's `flattenedVerify` function

Fix Webhook signature validation when JWS is malformed

---

src/middleware.ts

I want to merge this, because it allows to use stricter types for accepted `expectedEvent` type in `withSaleorEventMatch` middleware

Add types for event validation middleware

---

package.json
pnpm-lock.yaml

Don't think we require this package anymore - I was able to build and run watch mode without it.

Drop unused package `watchlist`

---

src/types.ts

I want to merge this because it adds types that can be used to make assertions for app's manifest.
For example:
```ts
// src/api/manifest.ts
import { AppManifest } from "@saleor/app-sdk/types";
const handler = (req, res) => {
const manifest = {
id: "saleor.checkout.app",
version: version,
name: appName,
about: "Saleor checkout app to quickly configure and customize checkout in your store.",
permissions: ["HANDLE_PAYMENTS", "HANDLE_CHECKOUTS", "MANAGE_ORDERS", "MANAGE_CHECKOUTS"],
appUrl: baseURL,
dataPrivacyUrl: `${baseURL}/data-privacy`,
supportUrl: `${baseURL}/support`,
tokenTargetUrl: `${baseURL}/api/register`,
} as AppManifest; // <- type assertion goes here
}
res.json(manifest);
}
export default handler;
```
If a developer would forget about a required field (for example `id`), they …

Add types for app manifest

---

src/types.ts

This PR fixes manifest types to use `asyncEvents` and `syncEvents` instead of `events` proerty. See https://github.com/saleor/saleor-docs/pull/542

Fix manifest type to use `asyncEvents` and `syncEvents`

---

src/app-bridge/app-bridge.ts

This is rquired because app-template broke when using app-sdk with previous
named import

Change "debug" package import to use default

---

src/app-bridge/app-bridge.ts
src/app-bridge/events.ts
src/headers.ts
src/middleware/with-jwt-verified.ts
src/middleware/with-registered-saleor-domain-header.ts
src/middleware/with-webhook-signature-verified.ts

- update types on headers helper function
- ignore type warnings in logging message
- use unknown instead of any for unknown events

Fix lint warnings

---

src/app-bridge/with-authorization.tsx

I've added `getLayout` to the return type of `withAuthorization`. Why? Because it turns out you need to apply `getLayout` after you wrap your component with `withAuthorization`. In the current situation TypeScript does not see `getLayout` on a wrapped component.
One example of such an error is [saleor-app-template](https://github.com/saleor/saleor-app-template/blob/main/pages/configuration.tsx#L133) - it turns out that the `Configuration` page will not have layout applied.
After a change in this PR following code will now work properly:
```tsx
function Component() {
return <div>Component here</div>;
}
const authorizedComponent = withAuthorization()(Component);
authorizedComponent.getLayout = () => (
<div>
<Component />
</div>
);
```

feat: add getLayout to return type of withAuthorization

---

package.json
tsup.config.ts

SDK contains many packages, including node & browser only. Current index import doesn't even work for browser, because it imports node-only code and it breaks.
Hence lets remove it and use tree-shakable imports from specific entry point.
Maybe related for next iteration: #92 
Before merging, lets check if apps work, otherwise fix imports first

Remove index export

---

src/APL/upstash-apl.test.ts

Existing env variables in my environment caused failing tests.

Remove variables from the env if are already existing in the upstash APL tests

---

src/handlers/next/process-async-saleor-webhook.ts
src/handlers/next/saleor-async-webhook.test.ts
src/handlers/next/saleor-async-webhook.ts

Event subscription in the manifest require query provided (unlike webhookCreate mutation)

`subscriptionQueryAst` or `query` argument has to be specified for the event subscriptions

---

docs/app-bridge.md
src/app-bridge/app-bridge-provider.test.tsx
src/app-bridge/app-bridge-state.test.ts
src/app-bridge/app-bridge-state.ts
src/app-bridge/app-bridge.ts
src/app-bridge/app-iframe-params.ts
src/app-bridge/index.ts
src/const.ts
src/handlers/next/process-async-saleor-webhook.test.ts
src/handlers/next/process-async-saleor-webhook.ts
src/handlers/next/saleor-async-webhook.ts
src/headers.ts
src/urls.ts
src/verify-signature.ts

This PR exposes access to new saleor-api-url header which is predictable URL for graphql
Ref #94

Add saleorApiUrl state param to AppBridge

---

docs/app-bridge.md
src/app-bridge/actions.ts
src/app-bridge/app-bridge.test.ts
src/app-bridge/app-bridge.ts
src/app-bridge/next/route-propagator.tsx

Context - when app is loaded it will be mounted in full height iframe, blinding with white/dark background (depending on app config) before theme is sent (after js loaded)
To avoid this situation, Dashboard should control when iframe is visible. Dashboard should show loading instead of iframe, and when app is loaded, show iframe
To achieve that, Dashboard must be informed when app is ready, hence new action `notifyReady` in SDK which is automatically sent when AppBridge is loaded (which means JS is loaded)

Add action that informs Dashboard that AppBridge is ready

---

docs/settings-manager.md
src/settings-manager/encrypted-metadata-manager.test.ts
src/settings-manager/encrypted-metadata-manager.ts

If the key is missing:
- for dev: use placeholder value and show the warning
- for production: log the error and exit the application due to misconfiguration

Handle missing encryption key for the EncryptedMetadataManager

---

src/handlers/next/saleor-async-webhook.test.ts
src/handlers/next/saleor-async-webhook.ts

So this is possible now:
```
onError(error, req) {
pino.log(req, error)
}
```

Add req and res to onError callback for AsyncWebhook

---

.changeset/sharp-yaks-rush.md
src/app-bridge/app-bridge.ts

To be merged after
https://github.com/saleor/saleor-dashboard/pull/3216
In this PR Dashboard handles this action and this is the default behaviour - App should inform that is ready to be displayed, then dashboard should initialize handshake

Change AppBridge default autoNotifyReady to true

---

.changeset/cool-knives-punch.md
src/headers.ts
src/middleware/with-base-url.test.ts

Some tunnel providers send multiple comma-separated values in `x-forwarded-proto` header. For example, in the case of ngrok it's `https,http`.
This PR introduces changes to handle such values correctly.

Support comma-delimited x-forwarded-proto

---

.changeset/slow-oranges-serve.md
docs/app-bridge.md
src/app-bridge/app-bridge.test.ts
src/app-bridge/app-bridge.ts
src/app-bridge/events.test.ts
src/app-bridge/events.ts

implemented in dashboard for testing
https://github.com/saleor/saleor-dashboard/pull/3683
Tested locally with Dashboard & Core (with 1 minute token). Token is passed properly

Add tokenRefresh event

---

.changeset/sixty-geese-whisper.md
src/APL/index.ts
src/APL/saleor-cloud/index.ts
src/APL/saleor-cloud/saleor-cloud-apl-errors.ts
src/APL/saleor-cloud/saleor-cloud-apl.test.ts
src/APL/saleor-cloud/saleor-cloud-apl.ts

Throw error if cloud apl GET fails

---

.changeset/mean-ligers-care.md
package.json
src/APL/index.ts
src/APL/vercel-kv/index.ts
tsup.config.ts

having index.ts that exports all APLs means that all files are evaluated, no matter which apl is included.
it causes app to break because of missing dependency of vercel kv, even is its not used

create sparate export for vercel kv apl

---

.changeset/violet-donuts-begin.md
.eslintrc
package.json
pnpm-lock.yaml
src/APL/saleor-cloud/paginator.test.ts
src/APL/saleor-cloud/paginator.ts
src/APL/saleor-cloud/saleor-cloud-apl.test.ts
src/APL/saleor-cloud/saleor-cloud-apl.ts

- Format with prettier
- Add limit=1000 for getAll requests in cloud apl
- Add paginator and option to configure limit

Add pagination and option to configure limit for CloudAPL

---

.changeset/large-weeks-switch.md
src/const.ts
src/handlers/next/create-manifest-handler.ts
src/handlers/next/saleor-webhooks/process-saleor-webhook.test.ts
src/handlers/next/saleor-webhooks/process-saleor-webhook.ts
src/handlers/next/saleor-webhooks/saleor-async-webhook.test.ts
src/handlers/next/saleor-webhooks/saleor-sync-webhook.test.ts
src/headers.ts

Parse the `saleor-schema-version` header and include the parsed version in the contexts of `createHandler` and `webhookFactory`. If the header is absent (Saleor version below 3.15), the version will default to 0. 
Connected [RFC](https://github.com/saleor/apps/issues/1213).

Parse saleor schema version and add it to context

---

.changeset/fair-ads-trade.md
package.json
src/handlers/next/saleor-webhooks/process-saleor-webhook.test.ts
src/handlers/next/saleor-webhooks/process-saleor-webhook.ts
src/util/index.ts
src/util/schema-version.test.ts
src/util/schema-version.ts

Fix wrong logic introduced in [0.49.0](https://github.com/saleor/app-sdk/releases/tag/v0.49.0): there is not header `saleor-schema-version` when app-sdk is processing saleor webhook. This header is only present on install request.
Now app-sdk will try to parse version from `version` field on GraphQL subscription [Event](https://docs.saleor.io/docs/3.x/api-storefront/miscellaneous/interfaces/event#code-style-fontweight-normal-eventbversionbcodestring-). If field is not present `null` will be returned.

Parse schema version when processing saleor webhook

---

.github/workflows/main.yml
package.json
pnpm-lock.yaml
src/settings-manager/metadata-manager.test.ts
vitest.config.ts

* Updated vitest from ancient version
* Created Codecov setup

Setup codecov & update vitest

---

.changeset/witty-carrots-occur.md
src/middleware/middleware-debug.ts
src/middleware/with-auth-token-required.ts
src/middleware/with-base-url.ts
src/middleware/with-jwt-verified.ts
src/middleware/with-registered-saleor-domain-header.ts
src/middleware/with-saleor-app.ts
src/middleware/with-saleor-event-match.ts
src/middleware/with-webhook-signature-verified.ts

Marked middlewares as deprecated to be removed in v1

Mark middlewares as depreacted

---

.changeset/rare-tools-change.md
package.json
src/handlers/actions/register-action-handler.ts
src/handlers/platforms/fetch-api/create-app-register-handler.test.ts
src/handlers/platforms/fetch-api/create-app-register-handler.ts
src/handlers/platforms/fetch-api/create-manifest-handler.test.ts
src/handlers/platforms/fetch-api/create-manifest-handler.ts
src/handlers/platforms/fetch-api/create-protected-handler.test.ts
src/handlers/platforms/fetch-api/create-protected-handler.ts
src/handlers/platforms/fetch-api/index.ts
src/handlers/platforms/fetch-api/platform-adapter.test.ts
src/handlers/platforms/fetch-api/platform-adapter.ts
src/handlers/platforms/fetch-api/saleor-webhooks/saleor-async-webhook.test.ts
src/handlers/platforms/fetch-api/saleor-webhooks/saleor-async-webhook.ts
src/handlers/platforms/fetch-api/saleor-webhooks/saleor-sync-webhook.test.ts
src/handlers/platforms/fetch-api/saleor-webhooks/saleor-sync-webhook.ts
src/handlers/platforms/fetch-api/saleor-webhooks/saleor-webhook.ts
src/handlers/platforms/next/create-app-register-handler.test.ts
src/handlers/platforms/next/create-manifest-handler.ts
src/handlers/platforms/next/platform-adapter.ts
src/handlers/platforms/next/saleor-webhooks/saleor-async-webhook.test.ts
src/handlers/shared/create-app-register-handler-types.ts
src/handlers/shared/generic-saleor-webhook.ts
src/handlers/shared/saleor-webhook.ts
tsup.config.ts

This PR adds handlers for Web API - Request and Response objects, used for example in Next.js Edge Runtime, hono, etc.
It also refactors comments for existing handlers and improves shared types.

Add Web API platform handlers

---

.changeset/serious-lamps-rhyme.md
package.json
pnpm-lock.yaml
src/handlers/platforms/aws-lambda/create-app-register-handler.test.ts
src/handlers/platforms/aws-lambda/create-app-register-handler.ts
src/handlers/platforms/aws-lambda/create-manifest-handler.test.ts
src/handlers/platforms/aws-lambda/create-manifest-handler.ts
src/handlers/platforms/aws-lambda/create-protected-handler.test.ts
src/handlers/platforms/aws-lambda/create-protected-handler.ts
src/handlers/platforms/aws-lambda/index.ts
src/handlers/platforms/aws-lambda/platform-adapter.test.ts
src/handlers/platforms/aws-lambda/platform-adapter.ts
src/handlers/platforms/aws-lambda/saleor-webhooks/saleor-async-webhook.ts
src/handlers/platforms/aws-lambda/saleor-webhooks/saleor-sync-webhook.test.ts
src/handlers/platforms/aws-lambda/saleor-webhooks/saleor-sync-webhook.ts
src/handlers/platforms/aws-lambda/saleor-webhooks/saleor-webhook.ts
src/handlers/platforms/aws-lambda/test-utils.ts
src/handlers/shared/generic-saleor-webhook.ts
tsup.config.ts

This PR adds handlers for AWS Lambda platform for events originating from HTTP events (e.g. Lambda URL, API Gateway).
Example implementation using this PR: https://github.com/witoszekdev/saleor-app-lambda-template

Add AWS Lambda handlers

---

.changeset/hip-queens-roll.md
.changeset/kind-zoos-raise.md
.changeset/rare-tools-change.md
.changeset/serious-lamps-rhyme.md
.changeset/silent-walls-heal.md
.changeset/sixty-taxis-glow.md

- **Add missing changeset**
- **Update changesets description, change scope**

Add missing changeset, add more description for changes

---

.changeset/tiny-maps-teach.md
package.json
src/handlers/platforms/next-app-router/create-manifest-handler.ts
src/handlers/platforms/next-app-router/create-protected-handler.ts
src/handlers/platforms/next-app-router/platform-adapter.ts
src/handlers/platforms/next-app-router/saleor-webhooks/saleor-sync-webhook.test.ts
src/handlers/platforms/next-app-router/saleor-webhooks/saleor-webhook.ts

https://arethetypeswrong.github.io/?p=%40saleor%2Fapp-sdk%400.0.0-pr-20250408085129

add next js filename suffix to fix esm
